/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.ngengine.NGEApplication;
import org.ngengine.components.ComponentManager;
import org.ngengine.gui.win.NWindowManagerComponent;
import org.ngengine.player.PlayerManagerComponent;
import com.jme3.system.AppSettings;

public class NGEAppMain {
    public static void main(String[] args) {
        AppSettings settings = new AppSettings(true);
        settings.setRenderer(AppSettings.LWJGL_OPENGL32);
        settings.setWidth(1280);
        settings.setHeight(720);
        settings.setGammaCorrection(true);
        settings.setSamples(4);
        settings.setStencilBits(8);
        settings.setDepthBits(24);
        settings.setVSync(true);
        settings.setGraphicsDebug(false);
        settings.setTitle("Nostr Game Engine Demo");
        

        Runnable appBuilder = NGEApplication.createApp(
            settings,
            app -> {
                ComponentManager mng = app.getComponentManager();
                mng.addAndEnableComponent(new PlayerManagerComponent());
                mng.addAndEnableComponent(new NWindowManagerComponent());

                // Add more components as needed
                // ...
            
                mng.addComponent(new MainComponent(), NWindowManagerComponent.class, PlayerManagerComponent.class);
                mng.enableComponent(MainComponent.class);
            }
        );
        appBuilder.run();
    }
}
